### ISSUE TITLE
Remove all boilerplate dependencies

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/devcon#4]

**Comment by pragmaticivan** [comment]
Should we still maintain this repo? cc @igr

**Comment by igr** [comment]
It should be not my decision @pragmaticivan.

We have built it for the Devcon workshop. It is rather short, so we have enough time to express everything. It was meant to be a workshop (so its not just a demo).

Not sure if I ever got feedback on this. I would not throw it away; but if we are gonna have the workshops just for the devcon, then we might remove it.

So just let me know!

**Comment by jonnilundy** [comment]
What do you guys think about renaming to `devcon-workshop` and then making the repo private?

**Comment by igr** [comment]
@jonnilundy repo can't be private as people are supposed to use it to fetch the code on the workshop.

**Comment by igr** [comment]
Closed. There was no real `boilerplate` dependency.
